-- Create a table for public profiles
create table profiles (
  id uuid not null references auth.users on delete cascade,
  full_name text,
  avatar_url text,
  website text,

  primary key (id)
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for content
create type content_type as enum ('link', 'text', 'file');

create table content (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  title text not null,
  content text not null,
  type content_type not null,
  category text,
  tags text[],
  created_at timestamptz default now(),
  analyzed boolean default false
);

alter table content enable row level security;

create policy "Users can view their own content."
  on content for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own content."
  on content for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own content."
  on content for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own content."
  on content for delete
  using ( auth.uid() = user_id );

-- Set up Realtime!
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table profiles;
alter publication supabase_realtime add table content;

-- This trigger automatically creates a profile for new users.
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();